/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
	applyconfigurationkueuev1alpha1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1alpha1"
	scheme "sigs.k8s.io/kueue/client-go/clientset/versioned/scheme"
)

// TestJobsGetter has a method to return a TestJobInterface.
// A group's client should implement this interface.
type TestJobsGetter interface {
	TestJobs(namespace string) TestJobInterface
}

// TestJobInterface has methods to work with TestJob resources.
type TestJobInterface interface {
	Create(ctx context.Context, testJob *kueuev1alpha1.TestJob, opts v1.CreateOptions) (*kueuev1alpha1.TestJob, error)
	Update(ctx context.Context, testJob *kueuev1alpha1.TestJob, opts v1.UpdateOptions) (*kueuev1alpha1.TestJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, testJob *kueuev1alpha1.TestJob, opts v1.UpdateOptions) (*kueuev1alpha1.TestJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kueuev1alpha1.TestJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*kueuev1alpha1.TestJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kueuev1alpha1.TestJob, err error)
	Apply(ctx context.Context, testJob *applyconfigurationkueuev1alpha1.TestJobApplyConfiguration, opts v1.ApplyOptions) (result *kueuev1alpha1.TestJob, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, testJob *applyconfigurationkueuev1alpha1.TestJobApplyConfiguration, opts v1.ApplyOptions) (result *kueuev1alpha1.TestJob, err error)
	TestJobExpansion
}

// testJobs implements TestJobInterface
type testJobs struct {
	*gentype.ClientWithListAndApply[*kueuev1alpha1.TestJob, *kueuev1alpha1.TestJobList, *applyconfigurationkueuev1alpha1.TestJobApplyConfiguration]
}

// newTestJobs returns a TestJobs
func newTestJobs(c *KueueV1alpha1Client, namespace string) *testJobs {
	return &testJobs{
		gentype.NewClientWithListAndApply[*kueuev1alpha1.TestJob, *kueuev1alpha1.TestJobList, *applyconfigurationkueuev1alpha1.TestJobApplyConfiguration](
			"testjobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kueuev1alpha1.TestJob { return &kueuev1alpha1.TestJob{} },
			func() *kueuev1alpha1.TestJobList { return &kueuev1alpha1.TestJobList{} },
		),
	}
}
