/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
)

// TestJobLister helps list TestJobs.
// All objects returned here must be treated as read-only.
type TestJobLister interface {
	// List lists all TestJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1alpha1.TestJob, err error)
	// TestJobs returns an object that can list and get TestJobs.
	TestJobs(namespace string) TestJobNamespaceLister
	TestJobListerExpansion
}

// testJobLister implements the TestJobLister interface.
type testJobLister struct {
	listers.ResourceIndexer[*kueuev1alpha1.TestJob]
}

// NewTestJobLister returns a new TestJobLister.
func NewTestJobLister(indexer cache.Indexer) TestJobLister {
	return &testJobLister{listers.New[*kueuev1alpha1.TestJob](indexer, kueuev1alpha1.Resource("testjob"))}
}

// TestJobs returns an object that can list and get TestJobs.
func (s *testJobLister) TestJobs(namespace string) TestJobNamespaceLister {
	return testJobNamespaceLister{listers.NewNamespaced[*kueuev1alpha1.TestJob](s.ResourceIndexer, namespace)}
}

// TestJobNamespaceLister helps list and get TestJobs.
// All objects returned here must be treated as read-only.
type TestJobNamespaceLister interface {
	// List lists all TestJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1alpha1.TestJob, err error)
	// Get retrieves the TestJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1alpha1.TestJob, error)
	TestJobNamespaceListerExpansion
}

// testJobNamespaceLister implements the TestJobNamespaceLister
// interface.
type testJobNamespaceLister struct {
	listers.ResourceIndexer[*kueuev1alpha1.TestJob]
}
