/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	batchv1 "k8s.io/api/batch/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TestJobStatusApplyConfiguration represents a declarative configuration of the TestJobStatus type for use
// with apply.
//
// TestJobStatus defines the observed state of TestJob.
type TestJobStatusApplyConfiguration struct {
	// active is the number of active pods.
	Active *int32 `json:"active,omitempty"`
	// ready is the number of active pods with a Ready condition.
	Ready *int32 `json:"ready,omitempty"`
	// succeeded is the number of pods which reached phase Succeeded.
	Succeeded *int32 `json:"succeeded,omitempty"`
	// failed is the number of pods which reached phase Failed.
	Failed *int32 `json:"failed,omitempty"`
	// startTime represents time when the first pod was created.
	StartTime *v1.Time `json:"startTime,omitempty"`
	// completionTime represents time when the TestJob completed successfully.
	CompletionTime *v1.Time `json:"completionTime,omitempty"`
	// conditions represent the latest available observations of the TestJob state.
	// The controller uses batch/v1 Job condition types intentionally, so Kueue tests
	// can exercise the same completion and failure paths as native Jobs.
	Conditions []batchv1.JobCondition `json:"conditions,omitempty"`
}

// TestJobStatusApplyConfiguration constructs a declarative configuration of the TestJobStatus type for use with
// apply.
func TestJobStatus() *TestJobStatusApplyConfiguration {
	return &TestJobStatusApplyConfiguration{}
}

// WithActive sets the Active field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Active field is set to the value of the last call.
func (b *TestJobStatusApplyConfiguration) WithActive(value int32) *TestJobStatusApplyConfiguration {
	b.Active = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *TestJobStatusApplyConfiguration) WithReady(value int32) *TestJobStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithSucceeded sets the Succeeded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Succeeded field is set to the value of the last call.
func (b *TestJobStatusApplyConfiguration) WithSucceeded(value int32) *TestJobStatusApplyConfiguration {
	b.Succeeded = &value
	return b
}

// WithFailed sets the Failed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Failed field is set to the value of the last call.
func (b *TestJobStatusApplyConfiguration) WithFailed(value int32) *TestJobStatusApplyConfiguration {
	b.Failed = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *TestJobStatusApplyConfiguration) WithStartTime(value v1.Time) *TestJobStatusApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *TestJobStatusApplyConfiguration) WithCompletionTime(value v1.Time) *TestJobStatusApplyConfiguration {
	b.CompletionTime = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TestJobStatusApplyConfiguration) WithConditions(values ...batchv1.JobCondition) *TestJobStatusApplyConfiguration {
	for i := range values {
		b.Conditions = append(b.Conditions, values[i])
	}
	return b
}
