/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// TestJobSpecApplyConfiguration represents a declarative configuration of the TestJobSpec type for use
// with apply.
//
// TestJobSpec defines the desired state of TestJob.
type TestJobSpecApplyConfiguration struct {
	// suspend controls whether the TestJob pod controller should create pods.
	Suspend *bool `json:"suspend,omitempty"`
	// parallelism is the maximum desired number of active pods.
	Parallelism *int32 `json:"parallelism,omitempty"`
	// completions is the desired number of successfully finished pods.
	// If unset, the TestJob keeps parallelism pods active.
	Completions *int32 `json:"completions,omitempty"`
	// template describes the pods that will be created by this TestJob.
	Template *v1.PodTemplateSpecApplyConfiguration `json:"template,omitempty"`
}

// TestJobSpecApplyConfiguration constructs a declarative configuration of the TestJobSpec type for use with
// apply.
func TestJobSpec() *TestJobSpecApplyConfiguration {
	return &TestJobSpecApplyConfiguration{}
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *TestJobSpecApplyConfiguration) WithSuspend(value bool) *TestJobSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithParallelism sets the Parallelism field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Parallelism field is set to the value of the last call.
func (b *TestJobSpecApplyConfiguration) WithParallelism(value int32) *TestJobSpecApplyConfiguration {
	b.Parallelism = &value
	return b
}

// WithCompletions sets the Completions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Completions field is set to the value of the last call.
func (b *TestJobSpecApplyConfiguration) WithCompletions(value int32) *TestJobSpecApplyConfiguration {
	b.Completions = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *TestJobSpecApplyConfiguration) WithTemplate(value *v1.PodTemplateSpecApplyConfiguration) *TestJobSpecApplyConfiguration {
	b.Template = value
	return b
}
